#this is not ready at all
version: '3.8'

services:
  database:
    container_name: postgres
    image: postgres:14-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod:
